version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    working_directory: ~/project
    steps:
      - checkout
      - run: gcc -o helloworld helloworld.c
workflows:
  version: 2
  build_and_test:
  jobs:
      - build
